os:
  - linux
  - osx
rust:
  - beta
language: rust
before_install: brew update || true ; brew upgrade postgresql || true || brew install postgresql
script:  make
addons:
  postgresql: "9.4"
  apt:
    packages:
    - libpq-dev
    - postgresql-server-dev-all
    - libclang1-3.4
    - libclang-3.4-dev
    - libclang-common-3.4-dev
    - clang-3.4
