language: rust
sudo: required
os:
  - linux
  - osx
rust:
  - beta

addons:
  apt:
    packages:
      - libpq-dev
      - postgresql-server-dev-all
      - libclang1-3.4
      - libclang-3.4-dev
      - libclang-common-3.4-dev
      - clang-3.4
  postgresql: "9.4"

before_install: ci_tools/prepare_${TRAVIS_OS_NAME}.sh
script: test/run_tests.sh
