[package]
name = "elephantpump-sys"
version = "0.1.0"
authors = ["Alex Newman <posi@planet.com>"]
build = "build.rs"


[dependencies]
libc = "*"

[build-dependencies]
pkg-config = "*"


[lib]
crate-type = ["dylib"]
